#!/bin/sh

#https://github.com/preservim/nerdtree - to see folders and files.

mkdir -p ~/.vim/pack/NERDTree/start/
git clone --depth 1 \
  https://github.com/preservim/nerdtree.git \
  ~/.vim/pack/NERDTree/start/NERDTree
