#!/bin/sh

# highlight words under curser.
mkdir -p ~/.vim/pack/plugins/start
cd ~/.vim/pack/plugins/start
git clone https://github.com/RRethy/vim-illuminate.git

#for using ctags and golang install https://github.com/jstemmer/gotags
